### ISSUE TITLE
회원 가입

### ISSUE THREAD

**Issue by dhchoi98** [f-lab-edu/sound-hub#5]
### 회원 가입

* 회원가입 기능에 필요한 Controller, Service와 Mapper 개발

**Comment by pjy1368** [comment]
이슈 단위는 가능한 작게 작게 분리 부탁드립니다 :)
ex) 회원 가입, 회원 정보 조회

**Comment by pjy1368** [comment]
적어주신 내용은 이슈보다는 요구 사항 명세서에 들어가는 것이 좋겠네요

**Comment by dhchoi98** [comment]
넵 알겠습니다!

**Comment by blue000927** [comment]
이슈 본문도 수정해주세요! 회원 가입에 관련된 내용들만~~
